"""
Requirements:
  pip install openai tiktoken numpy scikit-learn matplotlib
Set:
  export OPENAI_API_KEY="sk-..."
"""

import json
import os
import openai
import tiktoken
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt

# Load environment variables
from dotenv import load_dotenv
load_dotenv()

openai.api_key = os.getenv("OPENAI_API_KEY")
if openai.api_key is None:
    raise ValueError("Set OPENAI_API_KEY env var")

def merge_tokens_to_words(tokens, embeddings):
    words = []
    word_embs = []
    cur_tokens = []
    cur_embs = []
    for tok, emb in zip(tokens, embeddings):
        if tok.startswith(" "):  # new word begins (leading space)
            # flush previous
            if cur_tokens:
                words.append("".join(cur_tokens))
                word_embs.append(np.vstack(cur_embs).mean(axis=0))
            cur_tokens = [tok]
            cur_embs = [emb]
        else:
            # continuation subword (no leading space), append
            if not cur_tokens:
                cur_tokens = [tok]  # corner-case first token without leading space
                cur_embs = [emb]
            else:
                cur_tokens.append(tok)
                cur_embs.append(emb)
    # flush last
    if cur_tokens:
        words.append("".join(cur_tokens))
        word_embs.append(np.vstack(cur_embs).mean(axis=0))
    return words, np.vstack(word_embs)

with open('rcg/data/ngrams_simple.json', 'r') as f:
    ngrams = json.load(f)

traces = list(ngrams.values())[0]
for trace in traces:
    # -------------- user text --------------
    source_text = trace['prompt']

    # This could be generated by the model; here we show an example output_text:
    output_text = json.dumps(trace['code'])

    # -------------- tokenizer (use cl100k_base for OpenAI models) --------------
    enc = tiktoken.get_encoding("cl100k_base")

    # token ids
    src_ids = enc.encode(source_text)
    tgt_ids = enc.encode(output_text)

    # convert each token id back to readable string for labels
    # note: decoding single token gives string possibly with leading spaces — that's fine for labels
    src_tokens = [enc.decode([tid]) for tid in src_ids]
    tgt_tokens = [enc.decode([tid]) for tid in tgt_ids]

    # Option: merge subword tokens into words (not implemented here — we keep per-token)
    print(f"Source tokens ({len(src_tokens)}):", src_tokens)
    print(f"Target tokens ({len(tgt_tokens)}):", tgt_tokens)

    # -------------- get embeddings for each token string --------------
    # choose embeddings model (text-embedding-3-small or similar)
    EMB_MODEL = "text-embedding-3-small"

    def get_embeddings_for_token_list(tokens):
        # The API supports batch inputs; we pass the list of token strings
        # we call the embeddings endpoint and unpack the vectors.
        resp = openai.embeddings.create(model=EMB_MODEL, input=tokens)
        # resp.data is a list aligned with input tokens
        embeddings = np.array([item.embedding for item in resp.data], dtype=np.float32)
        return embeddings

    # For each token we ask for an embedding of that token's string
    # (Note: tokens often include leading space; that's OK and preserves token semantics)
    src_emb = get_embeddings_for_token_list(src_tokens)   # shape (src_len, dim)
    tgt_emb = get_embeddings_for_token_list(tgt_tokens)   # shape (tgt_len, dim)

    # src_tokens, src_emb = merge_tokens_to_words(src_tokens, src_emb)
    # tgt_tokens, tgt_emb = merge_tokens_to_words(tgt_tokens, tgt_emb)

    # -------------- compute similarity matrix --------------
    # We'll compute cosine similarity between each target token and every source token
    # result shape: (tgt_len, src_len)
    sim = cosine_similarity(tgt_emb, src_emb)  # rows: tgt tokens, cols: src tokens

    # Normalize per-target so rows sum to 1 (acts like attention distribution)
    sim_rownorm = sim / (sim.sum(axis=1, keepdims=True) + 1e-12)

    sim_max = sim_rownorm.max(axis=0)
    print(sim_max)

    # -------------- print top-K alignments per target token --------------
    K = 5
    topk_idx = np.argsort(sim_max)[::-1]
    for i, idx in enumerate(topk_idx):
        if not src_tokens[idx].strip():
            continue  # skip tokens that are just spaces
        print(f'{i+1}. {src_tokens[idx]} (sim={sim_max[idx]:.4f})')

    # -------------- plot heatmap --------------
    fig, ax = plt.subplots(figsize=(max(6, len(src_tokens)*0.35), max(4, len(tgt_tokens)*0.35)))
    im = ax.imshow(sim_rownorm, aspect='auto', interpolation='nearest')
    plt.colorbar(im, label="cosine similarity (row-normalized)")
    ax.set_xticks(np.arange(len(src_tokens)))
    ax.set_yticks(np.arange(len(tgt_tokens)))
    ax.set_xticklabels(src_tokens, rotation=90, fontsize=8)
    ax.set_yticklabels(tgt_tokens, fontsize=8)
    ax.set_xlabel("Source tokens")
    ax.set_ylabel("Target tokens")
    ax.set_title("Approx. input→output alignment via token embeddings")
    plt.tight_layout()
    plt.show()